name: On-demand self-hosted AWS EC2 runners for GitHub Actions
description: GitHub Action for automatic creation and registration AWS EC2 instances as GitHub Actions self-hosted runners.
author: Volodymyr Machula
branding:
  icon: 'box'
  color: 'orange'
inputs:
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start new runners;
        - 'stop' - to stop the previously created runners.
    required: true
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  key-pair-name:
    description: >-
      Key pair name to use when creating the runner instances.
      This input is required if you use the 'start' mode.
    required: false
  ec2-image-id:
    description: >-
      EC2 Image Id (AMI). The new runners will be launched from this image.
      This input is required if you use the 'start' mode.
    required: false
  ec2-instance-type:
    description: >-
      EC2 Instance Type.
      This input is required if you use the 'start' mode.
    required: false
  ec2-instance-count:
    description: >-
      Number of EC2 instances to create.
    required: false
    default: 1
  subnet-id:
    description: >-
      VPC Subnet Id. The subnet should belong to the same VPC as the specified security group.
      This input is required if you use the 'start' mode.
    required: false
  security-group-id:
    description: >-
      EC2 Security Group Id.
      The security group should belong to the same VPC as the specified subnet.
      The runners don't require any inbound traffic. However, outbound traffic should be allowed.
      This input is required if you use the 'start' mode.
    required: false
  label:
    description: >-
      Name of the unique label assigned to the runners.
      The label is used to remove the runners from GitHub when the runners are not needed anymore.
      This input is required if you use the 'stop' mode.
    required: false
  # This input's name is in the singular form for backwards compatibility
  ec2-instance-id:
    description: >-
      EC2 Instance Ids of the created runners.
      The ids are used to terminate the EC2 instances when the runners are not needed anymore.
      This input is required if you use the 'stop' mode. The value can either be in the form of
      a single raw string containing a single EC2 instance id, or a JSON-encoded string representing
      an array of id strings.
    required: false
  iam-role-name:
    description: >-
      IAM Role Name to attach to the created EC2 instances.
      This requires additional permissions on the AWS role used to launch instances.
    required: false
  aws-resource-tags:
    description: >-
      Tags to attach to the launched EC2 instances and volumes.
      This must be a stringified array of AWS Tag objects, with both Key and Value fields,
      for example: '[{"Key": "TagKey1", "Value": "TagValue1"}, {"Key": "TagKey2", "Value": "TagValue2"}]'
    required: false
    default: '[]'
  runner-home-dir:
    description: >-
      Directory that contains actions-runner software and scripts. E.g. /home/runner/actions-runner.
    required: false
  pre-runner-script:
    description: >-
      Specifies bash commands to run before the runner starts. It's useful for installing dependencies with apt-get, yum, dnf, etc.
    required: false
  market-type:
    description: >-
      Specifies the market (purchasing) option for the instance:
          - 'spot' - Use a spot instance
    required: false

outputs:
  label:
    description: >-
      Name of the unique label assigned to the runners.
      The label is used in two cases:
      - to use as the input of 'runs-on' property for the following jobs;
      - to remove the runners from GitHub when they are not needed anymore.
  # This output's name is in the singular form for backwards compatibility
  ec2-instance-id:
    description: >-
      EC2 Instance Ids of the created runners.
      The ids are used to terminate the EC2 instances when the runners are not needed anymore.
runs:
  using: node20
  main: ./dist/index.js
